### ISSUE TITLE
번역 가이드라인 초안

### ISSUE THREAD

**Issue by taggon** [nodejs/nodejs-ko#22]
#7 에서 논의된 내용을 바탕으로 다음과 같은 번역 가이드라인 초안을 잡아봤습니다. 자신의 의견과 다르거나 잘못된/수정해야 할 부분이 있으면 말씀해주세요.

---
# 번역자로 참여하는 방법
1. [translation 레이블이 붙은 이슈](https://github.com/iojs/iojs-kr/labels/translation) 중 아직 맡은 사람이 없는 것을 찾는다.
   만약, 번역하고자 하는 io.js 관련 글이 [이슈 트래커](https://github.com/iojs/iojs-kr/issues)에 등록되어 있지 않다면 직접 등록한다. 이 때, 이슈의 타이틀은 원본 글의 제목으로, 본문에는 원본 글의 링크를 입력한다. ( #20 참고 )
2.  [iojs-kr](https://github.com/iojs/iojs-kr) 프로젝트를 포크한다.
   - 원본 글을 주석으로 추가하고 원문 링크를 본문에 남겨 파일을 생성한다.
     - 주간 뉴스는 `weekly/_posts/` 아래 추가하고 파일명은 `YYYY-MM-DD-weekly.md` 형식을 사용한다.(예시: `2015-02-13-weekly.md`)
     - 다른 글은 `articles/_posts/` 아래 추가하고 파일명은 `YYYY-MM-DD-title.md`형식을 사용한다.(예시: `2015-01-27-state-of-io-js.md`)
     - 파일 상단에는 YAML 형식으로 글에 대한 메타정보를 작성한다.
     
     ```
     ---
     layout: post
     title: 번역글의 제목
     author: 원 저자명
     ref: 원문의 글 제목
     refurl: 원문 링크
     translator:
       - <a href="GITHUB_URL" target="_blank">번역자 이름</a>
     ---
     ```
     - 역자가 여러 명인 경우 `translator` 밑에 여러 줄로 추가한다.
   - 커밋 메시지에 해당 이슈 번호를 입력한 후 **번역 시작**을 알린다. 예를 들어 #00 번 이슈를 번역한다면 커밋 메시지를 다음과 같이 작성할 수 있다.
     - 주간 뉴스의 경우 > _번역 시작 : io.js Week of February 13th 2015 ( #00 )_
     - 일반적인 글의 경우 > _번역 시작 : State of io.js ( #00 )_
3. 시작일로부터 일정 기간 이내에 번역을 완료하지 못했다면 다른 사람이 번역할 수 있다. 마감 기한은 글마다 달라지는데 현재는 다음과 같이 설정되어 있다.
   - 주간 뉴스 : 1주
   - 일반적인 글 : 2주
4. 번역이 완료되면 시작할 때와 마찬가지로 커밋 메시지에 이슈 번호를 입력하여 **번역 완료**를 알린다.
   - 주간 뉴스의 경우 > _번역 완료 : io.js Week of February 13th 2015 ( #00 )_
   - 일반적인 글의 경우 > _번역 완료 : State of io.js ( #00 )_
5. 풀 리퀘스트를 통해 공식 저장소에 반영을 요청한다.
6. 번역된 글은 리뷰 과정을 거친 후 공식 저장소에 반영된다.
# 번역할 때 참고할 사항
1. 특별히 어색하지 않다면 기울임꼴, 굵은 글씨 등 서식은 원문과 똑같이 사용합니다.
2. 사람, 기관, 지역 이름은 가능한 영어 그대로 남겨둡니다.
3. 본문에 링크된 글에 대한 한국어 문서가 존재한다면 한국어 문서의 링크를 우선적으로 사용합니다.
4. 적어도 풀 리퀘스트를 만들기 전에는 [한국어 맞춤법 검사기](http://speller.cs.pusan.ac.kr/)를 사용해 맞춤법을 확인해주세요.
